-keep class com.syndx.app.data.local.entity.** { *; }
-keep class com.syndx.app.domain.model.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
-keep class retrofit2.** { *; }
-keep interface retrofit2.** { *; }
-keep class com.squareup.moshi.** { *; }
-keepclassmembers class * { @com.squareup.moshi.FromJson *; @com.squareup.moshi.ToJson *; }
-keep class com.google.firebase.** { *; }
